import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { URBAN_HORRORS_DEFINITIONS, createUrbanHorrorsDefinitions } from "../scripts/content.js";
import { loadAfflictionForgeContract } from "./support/core-contract-loader.js";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const { normalizeAfflictionDefinition, validateAfflictionDefinition, AFFLICTION_SEMANTIC_TAG_VOCABULARY, parseSemanticTag } = await loadAfflictionForgeContract(root);
const locales = Object.fromEntries(["de", "en"].map((lang) => [lang, JSON.parse(fs.readFileSync(path.join(root, "lang", `${lang}.json`), "utf8"))]));
const dcByLevel = new Map([[0,14],[1,15],[2,16],[3,18],[4,19],[5,20],[6,22],[7,23],[8,24],[9,26],[10,27],[11,28],[12,30],[13,31],[14,32],[15,34],[16,35],[17,36],[18,38],[19,39],[20,40]]);
function resolveLocale(rootObject, token) { assert.ok(token.startsWith("@i18n:")); return token.slice(6).split(".").reduce((value, part) => value?.[part], rootObject); }
function collectI18nTokens(value, output = []) { if (typeof value === "string" && value.startsWith("@i18n:")) output.push(value); else if (Array.isArray(value)) value.forEach((entry) => collectI18nTokens(entry, output)); else if (value && typeof value === "object") Object.values(value).forEach((entry) => collectI18nTokens(entry, output)); return output; }
function allStages() { return URBAN_HORRORS_DEFINITIONS.flatMap((definition) => definition.stages); }
test("0.1.0 ships 32 original urban afflictions", () => { assert.equal(URBAN_HORRORS_DEFINITIONS.length, 32); assert.deepEqual(new Set(URBAN_HORRORS_DEFINITIONS.map((d)=>d.afflictionType)), new Set(["disease","poison","curse"])); });
test("every definition validates against Affliction Forge schema v2", () => { const effectValidator=()=>({valid:true,issues:[]}); for (const source of URBAN_HORRORS_DEFINITIONS) { const definition=normalizeAfflictionDefinition(source); const report=validateAfflictionDefinition(definition,{effectValidator}); assert.equal(report.valid,true,`${definition.id}: ${report.issues.map((i)=>`${i.path}: ${i.message}`).join(" | ")}`); } });
test("all identities are unique", () => { const ids=new Set(); for(const d of URBAN_HORRORS_DEFINITIONS){ assert.ok(!ids.has(d.id)); ids.add(d.id); assert.equal(new Set(d.stages.map((s)=>s.id)).size,d.stages.length); } });
test("all entries use level-based DC baseline",()=>{ for(const d of URBAN_HORRORS_DEFINITIONS) assert.equal(d.checks[0].dc,dcByLevel.get(d.level),d.id); });
test("semantic tags are canonical, urban, and Creature Forge ready",()=>{ const creatures=new Set(), themes=new Set(), origins=new Set(), deliveries=new Set(); for(const d of URBAN_HORRORS_DEFINITIONS){ const ns=new Set(); assert.ok(d.themes.includes("habitat:urban"),`${d.id} lacks habitat:urban`); for(const tag of d.themes){ const p=parseSemanticTag(tag); assert.ok(p,`${d.id} non-semantic ${tag}`); assert.equal(p.canonical,true,tag); assert.ok(AFFLICTION_SEMANTIC_TAG_VOCABULARY[p.namespace].includes(p.value),tag); ns.add(p.namespace); if(p.namespace==="creature") creatures.add(p.value); if(p.namespace==="theme") themes.add(p.value); if(p.namespace==="origin") origins.add(p.value); if(p.namespace==="delivery") deliveries.add(p.value); } for(const req of ["creature","habitat","theme","origin","delivery"]) assert.ok(ns.has(req),`${d.id} lacks ${req}`); } for(const x of ["humanoid","undead","spirit","fungus","ooze","aberration","construct"]) assert.ok(creatures.has(x),`missing creature:${x}`); for(const x of ["disease","poison","curse","mental","shadow","corruption"]) assert.ok(themes.has(x),`missing theme:${x}`); for(const x of ["natural","alchemical","occult","undead","divine","technological"]) assert.ok(origins.has(x),`missing origin:${x}`); for(const x of ["inhaled","contact","ingested","weapon","injury","aura","ability"]) assert.ok(deliveries.has(x),`missing delivery:${x}`); });
test("exactly 6 true weapon coatings opt into injury-poison charges",()=>{ const coatings=URBAN_HORRORS_DEFINITIONS.filter((d)=>d.delivery?.injuryPoison===true); assert.equal(coatings.length,6); for(const d of coatings){ assert.equal(d.afflictionType,"poison"); assert.ok(d.themes.includes("delivery:weapon")); assert.ok(d.themes.includes("delivery:injury")); } });
test("library exercises advanced runtime mechanics",()=>{ const stages=allStages(); assert.ok(URBAN_HORRORS_DEFINITIONS.filter((d)=>d.progression?.virulent===true).length>=7); assert.ok(stages.some((s)=>s.effect?.components?.some((c)=>c.type==="damage"&&c.persistent===true))); assert.ok(stages.filter((s)=>s.preActionGates?.length).length>=6); assert.ok(stages.some((s)=>s.restrictions?.blockedCapabilities?.includes("speak"))); assert.ok(stages.some((s)=>s.restrictions?.conditionLocks?.length)); assert.ok(stages.some((s)=>s.restrictions?.healing==="affliction-damage")); assert.ok(stages.some((s)=>s.effect?.components?.some((c)=>c.type==="death"))); });
test("all i18n content tokens resolve in German and English",()=>{ const tokens=[...new Set(URBAN_HORRORS_DEFINITIONS.flatMap((d)=>collectI18nTokens(d)))]; assert.ok(tokens.length>120); for(const token of tokens) for(const lang of ["de","en"]){ const value=resolveLocale(locales[lang],token); assert.equal(typeof value,"string",`${lang} missing ${token}`); assert.ok(value.trim()); } });
test("definition factory returns independent clones",()=>{ const a=createUrbanHorrorsDefinitions(), b=createUrbanHorrorsDefinitions(); assert.notEqual(a[0],b[0]); a[0].name="mutated"; assert.notEqual(b[0].name,"mutated"); });
test("release tests contain no build-machine absolute imports",()=>{ const testsRoot=path.join(root,"tests"),files=[]; const visit=(dir)=>{ for(const e of fs.readdirSync(dir,{withFileTypes:true})){ const f=path.join(dir,e.name); if(e.isDirectory()) visit(f); else if(e.isFile()&&e.name.endsWith(".js")) files.push(f); } }; visit(testsRoot); for(const f of files){ const src=fs.readFileSync(f,"utf8"); assert.equal(src.includes("/mnt/data/"+"affliction_semantic"),false,path.relative(root,f)); assert.equal(/from\s+["'][A-Za-z]:[\\/]/.test(src),false,path.relative(root,f)); } });
